### ISSUE TITLE
Update eslint-config-trybe

### ISSUE THREAD

**Issue by EduardoSantosF** [betrybe/eslint-config-trybe#28]
Atualizei algumas regras de lint

**Comment by EduardoSantosF** [comment]
https://github.com/betrybe/eslint-config-trybe/pull/27

**Comment by robertotcestari** [comment]
Falta só publicar essa versão. 

- [ ] Mergear
- [ ] Publicar Pacote

Lembrando que ainda temos 2 bugs, mas vamos deixar para a próxima sprint/interação. 

- #26 
- #29

**Comment by robertotcestari** [comment]
@renatofreire depois pode fazer o publish aqui?

**Comment by robertotcestari** [comment]
@renatofreire pode publicar para fecharmos essa issue?

**Comment by robertotcestari** [comment]
Ei @renatofreire quando for publicar, aprova antes o #26 #31 ! 
Porque já corrige o último bug! 

Feito isso já podemos atualizar todos nossos projetos!
