### ISSUE TITLE
Ajustar complexidade ciclomática para switch/case no ESLint

### ISSUE THREAD

**Issue by renatosousafilho** [betrybe/eslint-config-trybe#7]
Considerando o exemplo abaixo:

```js
const fruta = '';
  switch (fruta) {
  case 'banana': break;
  case 'maçã': break;
  case 'pêra': break;
  case 'abacate': break;
  case 'laranja': break;
  default: break;
  }
```

A atual configuração do ESLint considera um código de nível de complexidade muito alta. Nesse caso, eu acho válido abrirmos uma excessão para esse cenário.

Para fazer isso basta usar a seguinte notação

```
"complexity": [
      true,
      5,
      {
        "ignoredClauses": [
          "caseClause"
        ]
      }
    ]
```

Usei como referência essa issue: https://github.com/palantir/tslint/issues/4436

**Comment by gfpoliva** [comment]
Faz sentido pra mim essa alteração.

**Comment by barraponto** [comment]
Acho que falta um pouco de contexto aqui:
* a regra não faz parte do `eslint/recommended` ou do `airbnb/base` `*`
* o valor padrão da regra é 20
* no `eslint-config-betrybe-frontend` o valor é definido como `15`
* `eslint-config-betrybe-fundamentals` e `eslint-config-betrybe-backend` definem como `5`

`*` na verdade o `airbnb/base` define como **desligado** e `11`, o que não faz muito sentido.

**Comment by renatosousafilho** [comment]
Pessoal, só fazendo uma correção, a solucão que mostrei mais cedo não funciona para ESLint, essa cláusula `ignoredClauses` não existe no ESLint. A issue que eu referenciei é para o TSLint.

Procurando por algo nas issues do ESLint o mais perto que encontrei foi essa aqui: https://github.com/eslint/eslint/issues/13881, mas ela foi fechada sem gerar nenhuma alteração.

Para Turma 6, deixei a regra valendo com 15 nós de complexidade ciclomática, fazendo jus com o que está no frontend.

**Comment by robertotcestari** [comment]
Pessoal, fechando aqui por inatividade (e de acordo com o que o @renatosousafilho pontuou). Fiquem à vontade para reabrirem a discussão.
